<%@ Page Title="Brewery Details" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Brewery.aspx.cs" Inherits="RememBeer.WebClient.Admin.Brewery" %>
<%@ Import Namespace="RememBeer.WebClient.Utils" %>
<%@ Register tagPrefix="uc" tagName="Notifier" src="../UserControls/UserNotifications.ascx" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <uc:Notifier runat="server" ID="Notifier"/>
    <div class="container">
        <div class="col-md-6 col-md-offset-3">
            <asp:DetailsView runat="server"
                             ID="BreweryDetails"
                             AutoGenerateEditButton="True"
                             AutoGenerateDeleteButton="True"
                             AutoGenerateInsertButton="True"
                             AutoGenerateRows="False"
                OnModeChanging="BreweryDetails_OnModeChanging"
                             ItemType="RememBeer.Models.Contracts.IBrewery"
                             CssClass="table table-responsive table-bordered table-striped table-hover table-condensed">
                <Fields>
                    <asp:BoundField AccessibleHeaderText="Id" DataField="Id" HeaderText="Id" ReadOnly="True"/>
                    <asp:BoundField AccessibleHeaderText="Name" DataField="Name" HeaderText="Name"/>
                    <asp:TemplateField HeaderText="Description" AccessibleHeaderText="Description">
                        <ItemTemplate>
                            <asp:Label ID="Label1" runat="server" Text='<%# this.Eval("Description").ToString().Truncate(200) %>'></asp:Label>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:TextBox runat="server" ID="DescrTb" CssClass="form-control" TextMode="MultiLine" Rows="3" Text='<%# Bind("Description") %>'></asp:TextBox>
                        </EditItemTemplate>                    
                    </asp:TemplateField>
                    <asp:BoundField AccessibleHeaderText="Country" DataField="Country" HeaderText="Country"/>
                </Fields>
            </asp:DetailsView>
        </div>
    </div>
</asp:Content>